// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {repos} from '../models';
import {merge} from '../models';
import {cmdlog} from '../models';
import {settings} from '../models';
import {gitlog} from '../models';
import {ai} from '../models';
import {worktree} from '../models';
import {gitsettings} from '../models';
import {refs} from '../models';
import {ops} from '../models';
import {stash} from '../models';
import {submodules} from '../models';
import {prompts} from '../models';
import {worktrees} from '../models';

export function AIStatus():Promise<app.AIStatus>;

export function AbortMerge(arg1:string):Promise<void>;

export function AddRepo():Promise<repos.Repo>;

export function CancelPull():Promise<void>;

export function Checkout(arg1:string,arg2:string):Promise<void>;

export function CheckoutDetached(arg1:string,arg2:string):Promise<void>;

export function CheckoutRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CherryPick(arg1:string,arg2:string):Promise<merge.Result>;

export function ClearChat(arg1:string):Promise<void>;

export function ClearCommandLog(arg1:string):Promise<void>;

export function CommandLog(arg1:string):Promise<Array<cmdlog.Entry>>;

export function CommandLogOutput(arg1:string,arg2:number):Promise<cmdlog.Output>;

export function CommitChanges(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CommitMerge(arg1:string):Promise<void>;

export function ConfirmChatAction(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreateBranch(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function CreateTag(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteBranch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteProviderKey(arg1:string):Promise<void>;

export function DeleteRemoteBranch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteTag(arg1:string,arg2:string):Promise<void>;

export function DiscardFile(arg1:string,arg2:string):Promise<void>;

export function ExplainInChat(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExplainLinesInChat(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:string):Promise<void>;

export function Fetch(arg1:string):Promise<void>;

export function Fingerprint(arg1:string):Promise<string>;

export function GenerateCommitMessage(arg1:string,arg2:string):Promise<void>;

export function GetAISettings():Promise<settings.Settings>;

export function GetAuthors(arg1:string):Promise<Array<string>>;

export function GetBlame(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<gitlog.Blame>;

export function GetChat(arg1:string):Promise<Array<ai.Message>>;

export function GetChatConfirm(arg1:string):Promise<app.ConfirmEvent>;

export function GetCommitPreview(arg1:string):Promise<worktree.CommitInfo>;

export function GetConflictFile(arg1:string,arg2:string):Promise<app.ConflictFile>;

export function GetDetails(arg1:string,arg2:string):Promise<gitlog.Details>;

export function GetDiff(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function GetGitSettings():Promise<gitsettings.Settings>;

export function GetIdentity(arg1:string):Promise<app.Identity>;

export function GetLog(arg1:string,arg2:gitlog.Filters,arg3:string,arg4:number,arg5:number):Promise<app.LogPage>;

export function GetMergeState(arg1:string):Promise<merge.State>;

export function GetRebasePreview(arg1:string,arg2:string):Promise<merge.Preview>;

export function GetRefs(arg1:string):Promise<refs.Refs>;

export function GetRemoteInfo(arg1:string):Promise<ops.AheadBehind>;

export function GetResetPreview(arg1:string,arg2:string):Promise<ops.ResetInfo>;

export function GetStashDiff(arg1:string,arg2:number):Promise<string>;

export function GetStashEntries(arg1:string):Promise<Array<stash.Entry>>;

export function GetStashFileDiff(arg1:string,arg2:number,arg3:string):Promise<string>;

export function GetStashFiles(arg1:string,arg2:number):Promise<Array<stash.File>>;

export function GetSubmodules(arg1:string):Promise<Array<submodules.Submodule>>;

export function GetWorktreeDiff(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GetWorktreeState(arg1:string):Promise<worktree.State>;

export function InitAllSubmodules(arg1:string):Promise<void>;

export function InitSubmodule(arg1:string,arg2:string):Promise<void>;

export function IsAncestorOfHead(arg1:string,arg2:string):Promise<boolean>;

export function IsShallow(arg1:string):Promise<boolean>;

export function ListModels(arg1:string):Promise<Array<string>>;

export function ListPrompts():Promise<Array<prompts.Info>>;

export function ListRepos():Promise<Array<app.RepoItem>>;

export function MergeBranch(arg1:string,arg2:string):Promise<merge.Result>;

export function OpenPromptsFolder():Promise<void>;

export function OpenRepoFolder(arg1:string):Promise<void>;

export function OwedStashDrop(arg1:string):Promise<number>;

export function Pull(arg1:string):Promise<ops.Result>;

export function PullModel(arg1:string):Promise<void>;

export function Push(arg1:string):Promise<void>;

export function RebaseOnto(arg1:string,arg2:string):Promise<merge.Result>;

export function RelocateRepo(arg1:string):Promise<repos.Repo>;

export function RemoveRepo(arg1:string):Promise<void>;

export function RemoveWorktree(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function RenameRepoGroup(arg1:string,arg2:string):Promise<void>;

export function ResetBranch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetPrompt(arg1:string):Promise<void>;

export function ResolveCommit(arg1:string,arg2:string):Promise<string>;

export function ResolveConflicts(arg1:string,arg2:string):Promise<void>;

export function SaveAISettings(arg1:settings.Settings):Promise<void>;

export function SaveGitSettings(arg1:gitsettings.Settings):Promise<void>;

export function SendChat(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetProviderKey(arg1:string,arg2:string):Promise<void>;

export function SetRepoGroup(arg1:string,arg2:string):Promise<void>;

export function SkipStep(arg1:string):Promise<void>;

export function StageFile(arg1:string,arg2:string):Promise<void>;

export function StageMergeFile(arg1:string,arg2:string):Promise<void>;

export function StashApply(arg1:string,arg2:number):Promise<void>;

export function StashDrop(arg1:string,arg2:number):Promise<void>;

export function StashPop(arg1:string,arg2:number):Promise<void>;

export function StashPush(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function StopChat(arg1:string):Promise<void>;

export function SyncSubmodule(arg1:string,arg2:string):Promise<void>;

export function TakeMergeSide(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TerminalClose(arg1:string):Promise<void>;

export function TerminalOpen(arg1:string,arg2:number,arg3:number):Promise<string>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalShell():Promise<string>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;

export function UnstageFile(arg1:string,arg2:string):Promise<void>;

export function UnstageMergeFile(arg1:string,arg2:string):Promise<void>;

export function UpdateAllSubmodules(arg1:string):Promise<void>;

export function UpdateSubmodule(arg1:string,arg2:string):Promise<void>;

export function WorktreeRemovalInfo(arg1:string):Promise<worktrees.RemovalInfo>;
