// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIStatus() {
  return window['go']['app']['App']['AIStatus']();
}

export function AbortMerge(arg1) {
  return window['go']['app']['App']['AbortMerge'](arg1);
}

export function AddRepo() {
  return window['go']['app']['App']['AddRepo']();
}

export function CancelPull() {
  return window['go']['app']['App']['CancelPull']();
}

export function Checkout(arg1, arg2) {
  return window['go']['app']['App']['Checkout'](arg1, arg2);
}

export function CheckoutDetached(arg1, arg2) {
  return window['go']['app']['App']['CheckoutDetached'](arg1, arg2);
}

export function CheckoutRemote(arg1, arg2, arg3) {
  return window['go']['app']['App']['CheckoutRemote'](arg1, arg2, arg3);
}

export function CherryPick(arg1, arg2) {
  return window['go']['app']['App']['CherryPick'](arg1, arg2);
}

export function ClearChat(arg1) {
  return window['go']['app']['App']['ClearChat'](arg1);
}

export function CommitChanges(arg1, arg2, arg3) {
  return window['go']['app']['App']['CommitChanges'](arg1, arg2, arg3);
}

export function CommitMerge(arg1) {
  return window['go']['app']['App']['CommitMerge'](arg1);
}

export function ConfirmChatAction(arg1, arg2, arg3) {
  return window['go']['app']['App']['ConfirmChatAction'](arg1, arg2, arg3);
}

export function CreateBranch(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateBranch'](arg1, arg2, arg3, arg4);
}

export function CreateTag(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateTag'](arg1, arg2, arg3, arg4);
}

export function DeleteBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteBranch'](arg1, arg2, arg3);
}

export function DeleteProviderKey(arg1) {
  return window['go']['app']['App']['DeleteProviderKey'](arg1);
}

export function DeleteRemoteBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteRemoteBranch'](arg1, arg2, arg3);
}

export function DeleteTag(arg1, arg2) {
  return window['go']['app']['App']['DeleteTag'](arg1, arg2);
}

export function DiscardFile(arg1, arg2) {
  return window['go']['app']['App']['DiscardFile'](arg1, arg2);
}

export function ExplainInChat(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExplainInChat'](arg1, arg2, arg3, arg4);
}

export function Fetch(arg1) {
  return window['go']['app']['App']['Fetch'](arg1);
}

export function Fingerprint(arg1) {
  return window['go']['app']['App']['Fingerprint'](arg1);
}

export function GenerateCommitMessage(arg1, arg2) {
  return window['go']['app']['App']['GenerateCommitMessage'](arg1, arg2);
}

export function GetAISettings() {
  return window['go']['app']['App']['GetAISettings']();
}

export function GetAuthors(arg1) {
  return window['go']['app']['App']['GetAuthors'](arg1);
}

export function GetBlame(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetBlame'](arg1, arg2, arg3, arg4);
}

export function GetChat(arg1) {
  return window['go']['app']['App']['GetChat'](arg1);
}

export function GetChatConfirm(arg1) {
  return window['go']['app']['App']['GetChatConfirm'](arg1);
}

export function GetCommitPreview(arg1) {
  return window['go']['app']['App']['GetCommitPreview'](arg1);
}

export function GetConflictFile(arg1, arg2) {
  return window['go']['app']['App']['GetConflictFile'](arg1, arg2);
}

export function GetDetails(arg1, arg2) {
  return window['go']['app']['App']['GetDetails'](arg1, arg2);
}

export function GetDiff(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetDiff'](arg1, arg2, arg3, arg4);
}

export function GetGitSettings() {
  return window['go']['app']['App']['GetGitSettings']();
}

export function GetLog(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetLog'](arg1, arg2, arg3, arg4, arg5);
}

export function GetMergeState(arg1) {
  return window['go']['app']['App']['GetMergeState'](arg1);
}

export function GetRebasePreview(arg1, arg2) {
  return window['go']['app']['App']['GetRebasePreview'](arg1, arg2);
}

export function GetRefs(arg1) {
  return window['go']['app']['App']['GetRefs'](arg1);
}

export function GetRemoteInfo(arg1) {
  return window['go']['app']['App']['GetRemoteInfo'](arg1);
}

export function GetResetPreview(arg1, arg2) {
  return window['go']['app']['App']['GetResetPreview'](arg1, arg2);
}

export function GetStashDiff(arg1, arg2) {
  return window['go']['app']['App']['GetStashDiff'](arg1, arg2);
}

export function GetStashEntries(arg1) {
  return window['go']['app']['App']['GetStashEntries'](arg1);
}

export function GetStashFileDiff(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetStashFileDiff'](arg1, arg2, arg3);
}

export function GetStashFiles(arg1, arg2) {
  return window['go']['app']['App']['GetStashFiles'](arg1, arg2);
}

export function GetSubmodules(arg1) {
  return window['go']['app']['App']['GetSubmodules'](arg1);
}

export function GetWorktreeDiff(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetWorktreeDiff'](arg1, arg2, arg3);
}

export function GetWorktreeState(arg1) {
  return window['go']['app']['App']['GetWorktreeState'](arg1);
}

export function InitAllSubmodules(arg1) {
  return window['go']['app']['App']['InitAllSubmodules'](arg1);
}

export function InitSubmodule(arg1, arg2) {
  return window['go']['app']['App']['InitSubmodule'](arg1, arg2);
}

export function IsAncestorOfHead(arg1, arg2) {
  return window['go']['app']['App']['IsAncestorOfHead'](arg1, arg2);
}

export function IsShallow(arg1) {
  return window['go']['app']['App']['IsShallow'](arg1);
}

export function ListModels(arg1) {
  return window['go']['app']['App']['ListModels'](arg1);
}

export function ListPrompts() {
  return window['go']['app']['App']['ListPrompts']();
}

export function ListRepos() {
  return window['go']['app']['App']['ListRepos']();
}

export function MergeBranch(arg1, arg2) {
  return window['go']['app']['App']['MergeBranch'](arg1, arg2);
}

export function OpenPromptsFolder() {
  return window['go']['app']['App']['OpenPromptsFolder']();
}

export function OpenRepoFolder(arg1) {
  return window['go']['app']['App']['OpenRepoFolder'](arg1);
}

export function OwedStashDrop(arg1) {
  return window['go']['app']['App']['OwedStashDrop'](arg1);
}

export function Pull(arg1) {
  return window['go']['app']['App']['Pull'](arg1);
}

export function PullModel(arg1) {
  return window['go']['app']['App']['PullModel'](arg1);
}

export function Push(arg1) {
  return window['go']['app']['App']['Push'](arg1);
}

export function RebaseOnto(arg1, arg2) {
  return window['go']['app']['App']['RebaseOnto'](arg1, arg2);
}

export function RelocateRepo(arg1) {
  return window['go']['app']['App']['RelocateRepo'](arg1);
}

export function RemoveRepo(arg1) {
  return window['go']['app']['App']['RemoveRepo'](arg1);
}

export function RemoveWorktree(arg1, arg2, arg3) {
  return window['go']['app']['App']['RemoveWorktree'](arg1, arg2, arg3);
}

export function RenameRepoGroup(arg1, arg2) {
  return window['go']['app']['App']['RenameRepoGroup'](arg1, arg2);
}

export function ResetBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResetBranch'](arg1, arg2, arg3);
}

export function ResetPrompt(arg1) {
  return window['go']['app']['App']['ResetPrompt'](arg1);
}

export function ResolveCommit(arg1, arg2) {
  return window['go']['app']['App']['ResolveCommit'](arg1, arg2);
}

export function ResolveConflicts(arg1, arg2) {
  return window['go']['app']['App']['ResolveConflicts'](arg1, arg2);
}

export function SaveAISettings(arg1) {
  return window['go']['app']['App']['SaveAISettings'](arg1);
}

export function SaveGitSettings(arg1) {
  return window['go']['app']['App']['SaveGitSettings'](arg1);
}

export function SendChat(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendChat'](arg1, arg2, arg3);
}

export function SetProviderKey(arg1, arg2) {
  return window['go']['app']['App']['SetProviderKey'](arg1, arg2);
}

export function SetRepoGroup(arg1, arg2) {
  return window['go']['app']['App']['SetRepoGroup'](arg1, arg2);
}

export function SkipStep(arg1) {
  return window['go']['app']['App']['SkipStep'](arg1);
}

export function StageFile(arg1, arg2) {
  return window['go']['app']['App']['StageFile'](arg1, arg2);
}

export function StageMergeFile(arg1, arg2) {
  return window['go']['app']['App']['StageMergeFile'](arg1, arg2);
}

export function StashApply(arg1, arg2) {
  return window['go']['app']['App']['StashApply'](arg1, arg2);
}

export function StashDrop(arg1, arg2) {
  return window['go']['app']['App']['StashDrop'](arg1, arg2);
}

export function StashPop(arg1, arg2) {
  return window['go']['app']['App']['StashPop'](arg1, arg2);
}

export function StashPush(arg1, arg2, arg3) {
  return window['go']['app']['App']['StashPush'](arg1, arg2, arg3);
}

export function StopChat(arg1) {
  return window['go']['app']['App']['StopChat'](arg1);
}

export function SyncSubmodule(arg1, arg2) {
  return window['go']['app']['App']['SyncSubmodule'](arg1, arg2);
}

export function TakeMergeSide(arg1, arg2, arg3) {
  return window['go']['app']['App']['TakeMergeSide'](arg1, arg2, arg3);
}

export function TerminalClose(arg1) {
  return window['go']['app']['App']['TerminalClose'](arg1);
}

export function TerminalOpen(arg1, arg2, arg3) {
  return window['go']['app']['App']['TerminalOpen'](arg1, arg2, arg3);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['app']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalShell() {
  return window['go']['app']['App']['TerminalShell']();
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['app']['App']['TerminalWrite'](arg1, arg2);
}

export function UnstageFile(arg1, arg2) {
  return window['go']['app']['App']['UnstageFile'](arg1, arg2);
}

export function UnstageMergeFile(arg1, arg2) {
  return window['go']['app']['App']['UnstageMergeFile'](arg1, arg2);
}

export function UpdateAllSubmodules(arg1) {
  return window['go']['app']['App']['UpdateAllSubmodules'](arg1);
}

export function UpdateSubmodule(arg1, arg2) {
  return window['go']['app']['App']['UpdateSubmodule'](arg1, arg2);
}

export function WorktreeRemovalInfo(arg1) {
  return window['go']['app']['App']['WorktreeRemovalInfo'](arg1);
}
