// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {repos} from '../models';
import {settings} from '../models';
import {ai} from '../models';
import {gitlog} from '../models';
import {merge} from '../models';
import {refs} from '../models';
import {prompts} from '../models';

export function AIStatus():Promise<app.AIStatus>;

export function AbortMerge(arg1:string):Promise<void>;

export function AddRepo():Promise<repos.Repo>;

export function CancelPull():Promise<void>;

export function Checkout(arg1:string,arg2:string):Promise<void>;

export function CheckoutDetached(arg1:string,arg2:string):Promise<void>;

export function CheckoutRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ClearChat(arg1:string):Promise<void>;

export function CommitMerge(arg1:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function CreateTag(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteBranch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteRemoteBranch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteTag(arg1:string,arg2:string):Promise<void>;

export function ExplainInChat(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Fetch(arg1:string):Promise<void>;

export function Fingerprint(arg1:string):Promise<string>;

export function GetAISettings():Promise<settings.Settings>;

export function GetAuthors(arg1:string):Promise<Array<string>>;

export function GetChat(arg1:string):Promise<Array<ai.Message>>;

export function GetConflictFile(arg1:string,arg2:string):Promise<app.ConflictFile>;

export function GetDetails(arg1:string,arg2:string):Promise<gitlog.Details>;

export function GetDiff(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function GetLog(arg1:string,arg2:gitlog.Filters,arg3:number,arg4:number):Promise<app.LogPage>;

export function GetMergeState(arg1:string):Promise<merge.State>;

export function GetRefs(arg1:string):Promise<refs.Refs>;

export function IsShallow(arg1:string):Promise<boolean>;

export function ListPrompts():Promise<Array<prompts.Info>>;

export function ListRepos():Promise<Array<app.RepoItem>>;

export function MergeBranch(arg1:string,arg2:string):Promise<merge.Result>;

export function OpenPromptsFolder():Promise<void>;

export function Pull(arg1:string):Promise<void>;

export function PullModel(arg1:string):Promise<void>;

export function RelocateRepo(arg1:string):Promise<repos.Repo>;

export function RemoveRepo(arg1:string):Promise<void>;

export function ResetPrompt(arg1:string):Promise<void>;

export function ResolveCommit(arg1:string,arg2:string):Promise<string>;

export function ResolveConflicts(arg1:string,arg2:string):Promise<void>;

export function SaveAISettings(arg1:settings.Settings):Promise<void>;

export function SendChat(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StageMergeFile(arg1:string,arg2:string):Promise<void>;

export function StopChat(arg1:string):Promise<void>;

export function UnstageMergeFile(arg1:string,arg2:string):Promise<void>;
