// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo() {
  return window['go']['app']['App']['AddRepo']();
}

export function Checkout(arg1, arg2) {
  return window['go']['app']['App']['Checkout'](arg1, arg2);
}

export function CheckoutDetached(arg1, arg2) {
  return window['go']['app']['App']['CheckoutDetached'](arg1, arg2);
}

export function CheckoutRemote(arg1, arg2, arg3) {
  return window['go']['app']['App']['CheckoutRemote'](arg1, arg2, arg3);
}

export function CreateBranch(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateBranch'](arg1, arg2, arg3, arg4);
}

export function CreateTag(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateTag'](arg1, arg2, arg3, arg4);
}

export function DeleteBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteBranch'](arg1, arg2, arg3);
}

export function DeleteRemoteBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteRemoteBranch'](arg1, arg2, arg3);
}

export function DeleteTag(arg1, arg2) {
  return window['go']['app']['App']['DeleteTag'](arg1, arg2);
}

export function Fetch(arg1) {
  return window['go']['app']['App']['Fetch'](arg1);
}

export function Fingerprint(arg1) {
  return window['go']['app']['App']['Fingerprint'](arg1);
}

export function GetAuthors(arg1) {
  return window['go']['app']['App']['GetAuthors'](arg1);
}

export function GetDetails(arg1, arg2) {
  return window['go']['app']['App']['GetDetails'](arg1, arg2);
}

export function GetDiff(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetDiff'](arg1, arg2, arg3, arg4);
}

export function GetLog(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetLog'](arg1, arg2, arg3, arg4);
}

export function GetRefs(arg1) {
  return window['go']['app']['App']['GetRefs'](arg1);
}

export function IsShallow(arg1) {
  return window['go']['app']['App']['IsShallow'](arg1);
}

export function ListRepos() {
  return window['go']['app']['App']['ListRepos']();
}

export function Pull(arg1) {
  return window['go']['app']['App']['Pull'](arg1);
}

export function RelocateRepo(arg1) {
  return window['go']['app']['App']['RelocateRepo'](arg1);
}

export function RemoveRepo(arg1) {
  return window['go']['app']['App']['RemoveRepo'](arg1);
}

export function ResolveCommit(arg1, arg2) {
  return window['go']['app']['App']['ResolveCommit'](arg1, arg2);
}
