import * as Go from '../../wailsjs/go/app/App'
import type { AIMessage, AISettings, AIStatus, AheadBehind, AutoFetchResult, Blame, ChatConfirmEvent, CommandLogView, CommandOutput, CommitInfo, ConflictFile, Details, Filters, Flow, FlowConfig, FlowFinishResult, FlowPlan, FlowStartResult, FlowType, GitSettings, HunkAction, HunkPick, Identity, LogOrder, LogPage, MergeResult, MergeState, ProviderName, PromptInfo, PullResult, RebasePreview, RegionChoice, RegionResult, Refs, Repo, ResetInfo, ResetMode, StashEntry, StashFile, Submodule, WorktreeDiff, WorktreeRemovalInfo, WorktreeState } from './types'
import type { NotifyTarget } from './notifyRules'

// The generated bindings use Wails model classes; the JSON is identical to our
// interfaces, so cast at this single boundary.
const call = <T>(p: Promise<unknown>) => p as Promise<T>

export const api = {
  listRepos: () => call<Repo[]>(Go.ListRepos()),
  addRepo: () => call<Repo>(Go.AddRepo()),
  relocateRepo: (id: string) => call<Repo>(Go.RelocateRepo(id)),
  openRepoFolder: (id: string) => call<void>(Go.OpenRepoFolder(id)),
  openRepoTerminal: (id: string) => call<void>(Go.OpenRepoTerminal(id)),
  removeRepo: (id: string) => call<void>(Go.RemoveRepo(id)),
  getWorktreeRemovalInfo: (id: string) => call<WorktreeRemovalInfo>(Go.WorktreeRemovalInfo(id)),
  removeWorktree: (id: string, force: boolean, deleteBranch: boolean) => call<void>(Go.RemoveWorktree(id, force, deleteBranch)),
  setRepoGroup: (id: string, group: string) => call<void>(Go.SetRepoGroup(id, group)),
  renameRepoGroup: (oldName: string, newName: string) => call<void>(Go.RenameRepoGroup(oldName, newName)),
  reorderRepos: (ids: string[]) => call<void>(Go.ReorderRepos(ids)),

  getRefs: (id: string) => call<Refs>(Go.GetRefs(id)),
  getLog: (id: string, filters: Filters, order: LogOrder, offset: number, limit: number) =>
    call<LogPage>(Go.GetLog(id, filters as any, order, offset, limit)),
  getDetails: (id: string, hash: string) => call<Details>(Go.GetDetails(id, hash)),
  getDiff: (id: string, parent: string, hash: string, paths: string[]) => call<string>(Go.GetDiff(id, parent, hash, paths)),
  getBlame: (id: string, rev: string, path: string, ignoreWhitespace: boolean) => call<Blame>(Go.GetBlame(id, rev, path, ignoreWhitespace)),
  getAuthors: (id: string) => call<string[]>(Go.GetAuthors(id)),
  getIdentity: (id: string) => call<Identity>(Go.GetIdentity(id)),
  resolveCommit: (id: string, text: string) => call<string>(Go.ResolveCommit(id, text)),
  isShallow: (id: string) => call<boolean>(Go.IsShallow(id)),
  fingerprint: (id: string) => call<string>(Go.Fingerprint(id)),

  terminalOpen: (repoId: string, cols: number, rows: number) => call<string>(Go.TerminalOpen(repoId, cols, rows)),
  terminalWrite: (tab: string, data: string) => call<void>(Go.TerminalWrite(tab, data)),
  terminalResize: (tab: string, cols: number, rows: number) => call<void>(Go.TerminalResize(tab, cols, rows)),
  terminalClose: (tab: string) => call<void>(Go.TerminalClose(tab)),
  terminalShell: () => call<string>(Go.TerminalShell()),

  commandLog: (id: string) => call<CommandLogView>(Go.CommandLog(id)),
  commandLogOutput: (id: string, entryId: number) => call<CommandOutput>(Go.CommandLogOutput(id, entryId)),
  notify: (n: { id: string; title: string; body: string; repoID: string; target: NotifyTarget }) => call<void>(Go.Notify(n as any)),
  notificationStatus: () => call<string>(Go.NotificationStatus()),
  clearCommandLog: (id: string) => call<void>(Go.ClearCommandLog(id)),
  cancelCommand: (id: string, entryId: number) => call<void>(Go.CancelCommand(id, entryId)),

  checkout: (id: string, branch: string) => call<void>(Go.Checkout(id, branch)),
  /** Resolves to an ops.CheckoutOutcome: created, switched, fastForwarded or diverged. */
  checkoutRemote: (id: string, remote: string, name: string) => call<string>(Go.CheckoutRemote(id, remote, name)),
  checkoutDetached: (id: string, hash: string) => call<void>(Go.CheckoutDetached(id, hash)),
  resetBranch: (id: string, hash: string, mode: ResetMode) => call<void>(Go.ResetBranch(id, hash, mode)),
  getResetPreview: (id: string, hash: string) => call<ResetInfo>(Go.GetResetPreview(id, hash)),
  fetch: (id: string) => call<void>(Go.Fetch(id)),
  autoFetch: (id: string) => call<AutoFetchResult>(Go.AutoFetch(id)),
  autoFetchPaused: (id: string) => call<string[]>(Go.AutoFetchPaused(id)),
  push: (id: string) => call<void>(Go.Push(id)),
  pull: (id: string) => call<PullResult>(Go.Pull(id)),
  getRemoteInfo: (id: string) => call<AheadBehind>(Go.GetRemoteInfo(id)),
  branchCounts: (id: string, branch: string) => call<AheadBehind>(Go.BranchCounts(id, branch)),
  getGitSettings: () => call<GitSettings>(Go.GetGitSettings()),
  saveGitSettings: (s: GitSettings) => call<void>(Go.SaveGitSettings(s as any)),

  getStashEntries: (id: string) => call<StashEntry[]>(Go.GetStashEntries(id)),
  stashPush: (id: string, message: string, includeUntracked: boolean) => call<void>(Go.StashPush(id, message, includeUntracked)),
  stashApply: (id: string, index: number) => call<void>(Go.StashApply(id, index)),
  stashPop: (id: string, index: number) => call<void>(Go.StashPop(id, index)),
  stashDrop: (id: string, index: number) => call<void>(Go.StashDrop(id, index)),
  getStashDiff: (id: string, index: number) => call<string>(Go.GetStashDiff(id, index)),
  getStashFiles: (id: string, index: number) => call<StashFile[]>(Go.GetStashFiles(id, index)),
  getStashFileDiff: (id: string, index: number, path: string) => call<string>(Go.GetStashFileDiff(id, index, path)),
  owedStashDrop: (id: string) => call<number>(Go.OwedStashDrop(id)),

  createBranch: (id: string, name: string, target: string, checkout: boolean) =>
    call<void>(Go.CreateBranch(id, name, target, checkout)),
  deleteBranch: (id: string, name: string, force: boolean) => call<void>(Go.DeleteBranch(id, name, force)),
  deleteRemoteBranch: (id: string, remote: string, name: string) => call<void>(Go.DeleteRemoteBranch(id, remote, name)),
  createTag: (id: string, name: string, target: string, message: string) => call<void>(Go.CreateTag(id, name, target, message)),
  deleteTag: (id: string, name: string) => call<void>(Go.DeleteTag(id, name)),

  mergeBranch: (id: string, branch: string) => call<MergeResult>(Go.MergeBranch(id, branch)),
  getFlow: (id: string) => call<Flow>(Go.GetFlow(id)),
  initFlow: (id: string, cfg: FlowConfig) => call<void>(Go.InitFlow(id, cfg as any)),
  startFlow: (id: string, type: FlowType, name: string, base: string) => call<FlowStartResult>(Go.StartFlow(id, type, name, base)),
  planFinish: (id: string, branch: string, releases: string[]) => call<FlowPlan>(Go.PlanFinish(id, branch, releases)),
  finishFlow: (id: string, branch: string, releases: string[]) => call<FlowFinishResult>(Go.FinishFlow(id, branch, releases)),
  rebaseOnto: (id: string, onto: string) => call<MergeResult>(Go.RebaseOnto(id, onto)),
  getRebasePreview: (id: string, onto: string) => call<RebasePreview>(Go.GetRebasePreview(id, onto)),
  cherryPick: (id: string, rev: string) => call<MergeResult>(Go.CherryPick(id, rev)),
  skipStep: (id: string) => call<void>(Go.SkipStep(id)),
  isAncestorOfHead: (id: string, rev: string) => call<boolean>(Go.IsAncestorOfHead(id, rev)),
  getMergeState: (id: string) => call<MergeState>(Go.GetMergeState(id)),
  abortMerge: (id: string) => call<void>(Go.AbortMerge(id)),
  commitMerge: (id: string, message: string) => call<void>(Go.CommitMerge(id, message)),
  getMergeMessage: (id: string) => call<string>(Go.GetMergeMessage(id)),
  resolveConflicts: (repoID: string, runID: string) => call<void>(Go.ResolveConflicts(repoID, runID)),
  getConflictFile: (id: string, path: string) => call<ConflictFile>(Go.GetConflictFile(id, path)),
  stageMergeFile: (id: string, path: string) => call<void>(Go.StageMergeFile(id, path)),
  unstageMergeFile: (id: string, path: string) => call<void>(Go.UnstageMergeFile(id, path)),
  takeMergeSide: (id: string, path: string, side: 'ours' | 'theirs') => call<void>(Go.TakeMergeSide(id, path, side)),
  resolveMergeRegion: (id: string, path: string, region: string, choice: RegionChoice, text: string) => call<RegionResult>(Go.ResolveMergeRegion(id, path, region, choice, text)),
  restartConflictFile: (id: string, path: string) => call<void>(Go.RestartConflictFile(id, path)),
  chooseRegionOption: (repoID: string, callID: string, option: number, text: string) => call<RegionResult>(Go.ChooseRegionOption(repoID, callID, option, text)),

  getWorktreeState: (id: string) => call<WorktreeState>(Go.GetWorktreeState(id)),
  stageFile: (id: string, path: string) => call<void>(Go.StageFile(id, path)),
  unstageFile: (id: string, path: string) => call<void>(Go.UnstageFile(id, path)),
  discardFile: (id: string, path: string) => call<void>(Go.DiscardFile(id, path)),
  getWorktreeDiff: (id: string, path: string, staged: boolean) => call<WorktreeDiff>(Go.GetWorktreeDiff(id, path, staged)),
  applyHunkSelection: (id: string, path: string, staged: boolean, hash: string, picks: HunkPick[], action: HunkAction) =>
    call<void>(Go.ApplyHunkSelection(id, path, staged, hash, picks, action)),
  undoDiscard: (id: string) => call<void>(Go.UndoDiscard(id)),
  getCommitPreview: (id: string) => call<CommitInfo>(Go.GetCommitPreview(id)),
  commitChanges: (id: string, message: string, amend: boolean) => call<void>(Go.CommitChanges(id, message, amend)),
  generateCommitMessage: (id: string, runID: string) => call<void>(Go.GenerateCommitMessage(id, runID)),

  aiStatus: () => call<AIStatus>(Go.AIStatus()),
  getAISettings: () => call<AISettings>(Go.GetAISettings()),
  saveAISettings: (s: AISettings) => call<void>(Go.SaveAISettings(s as any)),
  pullModel: (name: string) => call<void>(Go.PullModel(name)),
  cancelPull: () => call<void>(Go.CancelPull()),
  listModels: (provider: string) => call<string[]>(Go.ListModels(provider)),
  setProviderKey: (provider: string, key: string) => call<void>(Go.SetProviderKey(provider, key)),
  deleteProviderKey: (provider: string) => call<void>(Go.DeleteProviderKey(provider)),
  getChat: (repoID: string) => call<AIMessage[]>(Go.GetChat(repoID)),
  sendChat: (repoID: string, text: string, runID: string) => call<void>(Go.SendChat(repoID, text, runID)),
  stopChat: (repoID: string) => call<void>(Go.StopChat(repoID)),
  confirmChatAction: (repoID: string, confirmID: string, approve: boolean) => call<void>(Go.ConfirmChatAction(repoID, confirmID, approve)),
  getChatConfirm: (repoID: string) => call<ChatConfirmEvent | null>(Go.GetChatConfirm(repoID) as Promise<ChatConfirmEvent | null>),
  clearChat: (repoID: string) => call<void>(Go.ClearChat(repoID)),
  explainInChat: (repoID: string, hash: string, provider: '' | ProviderName, runID: string) =>
    call<void>(Go.ExplainInChat(repoID, hash, provider, runID)),
  explainLinesInChat: (repoID: string, rev: string, path: string, start: number, end: number, provider: '' | ProviderName, runID: string) =>
    call<void>(Go.ExplainLinesInChat(repoID, rev, path, start, end, provider, runID)),
  listPrompts: () => call<PromptInfo[]>(Go.ListPrompts()),
  openPromptsFolder: () => call<void>(Go.OpenPromptsFolder()),
  resetPrompt: (name: string) => call<void>(Go.ResetPrompt(name)),

  getSubmodules: (id: string) => call<Submodule[]>(Go.GetSubmodules(id)),
  initSubmodule: (id: string, path: string) => call<void>(Go.InitSubmodule(id, path)),
  updateSubmodule: (id: string, path: string) => call<void>(Go.UpdateSubmodule(id, path)),
  syncSubmodule: (id: string, path: string) => call<void>(Go.SyncSubmodule(id, path)),
  initAllSubmodules: (id: string) => call<void>(Go.InitAllSubmodules(id)),
  updateAllSubmodules: (id: string) => call<void>(Go.UpdateAllSubmodules(id)),
}
